---
- name: Copy named.conf.options
  ansible.builtin.template:
    src: master.named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify:
    - Restart bind9

- name: Copy named.conf.local
  ansible.builtin.template:
    src: master.named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644
  notify:
    - Restart bind9

- name: Copy db file for zone
  ansible.builtin.template:
    src: master.db.j2
    dest: /etc/bind/db.{{ bind9_zone }}
    owner: root
    group: bind
    mode: 0644
  notify:
    - Restart bind9
