---
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
  default_box: generic/ubuntu2004
platforms:
  - name: dns-server-master
    interfaces:
      - network_name: private_network
        ip: 192.168.56.110
  - name: dns-server-slave-1
    interfaces:
      - network_name: private_network
        ip: 192.168.56.120
  - name: dns-client-1
    interfaces:
      - network_name: private_network
        ip: 192.168.56.210
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory.yml
verifier:
  name: testinfra
  options:
      verbose: true

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy