---
- name: Copy resolved.conf
  ansible.builtin.template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart systemd-resolved
